pipeline {
    agent any
    
    parameters {
        string(name: 'ProjectKey', defaultValue: 'petclinic', description: 'SonarQube project key')
        string(name: 'ProjectName', defaultValue: 'petclinic', description: 'SonarQube project name')
        string(name: 'SonarHostUrl', defaultValue: 'http://192.168.201.13:9000', description: 'SonarQube server URL')
       //string(name: 'SlackChannel', defaultValue: '#jenkins-build-sonar', description: 'Slack channel to send notifications')
       //string(name: 'SlackTokenCredentialId', defaultValue: 'SLACK-TOKEN', description: 'Slack token credential ID')
        string(name: 'GIT_REPO_URL', defaultValue: 'https://github.com/Noah-linux/docker-lab.git', description: 'Git repository URL')
        string(name: 'GIT_BRANCH', defaultValue: 'master', description: 'Git branch name')
    }

        environment {
        registry = "noaalinux/petclinic-java" // Docker image name
        registryCredential = 'Jenkins-Docker-Token' // Jenkins credential ID for DockerHub
        dockerImage = '' // Placeholder for Docker image object
        dockerTag = "${env.BUILD_NUMBER}" // Use build number as Docker tag
    }
    stages {
        stage('Checkout GitHub Repo') {
            steps {
                git 'https://github.com/Noah-linux/docker-lab.git' // Clone the GitHub repository
            }
        }

        stage('Compile Code') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn compile' // Compile the code
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn test' // Run the tests
                }
            }
        }

        stage('Build Package') {
            steps {
                dir('petclinic-app') {
                    sh 'mvn -Dmaven.test.failure.ignore=true clean package' // Build the package
                }
            }
        }

        stage('Sonar Static Code Analysis') {
            steps {
                dir('petclinic-app') { // Ensure SonarQube runs within the project directory
                    withCredentials([string(credentialsId: 'jenkins-sonar-token', variable: 'sonar_token')]) {
                        sh """
                        mvn sonar:sonar \
                            -Dsonar.projectKey=${params.ProjectKey} \
                            -Dsonar.projectName='${params.ProjectName}' \
                            -Dsonar.host.url=${params.SonarHostUrl} \
                            -Dsonar.login=${sonar_token}
                        """
                    }
                }
            }
        }
            stage('Docker Pull & Deploy') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', registryCredential) {
                        // Stop any existing container on the same port
                        sh """
                        docker ps -q --filter "name=petclinic" | grep -q . && docker stop petclinic && docker rm petclinic || true
                        """

                        // Pull the Docker image and run the container
                        echo "Pulling Docker image: ${registry}:${dockerTag} from DockerHub"
                        sh """
                        docker pull ${registry}:${dockerTag}
                        docker run -d -p 8081:8081 --name petclinic ${registry}:${dockerTag}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            dir('petclinic-app') {
                junit '**/target/surefire-reports/TEST-*.xml' // Archive JUnit test results
                archiveArtifacts 'target/*.jar' // Archive JAR files
            }
        }

        //always {
         //   slackSend (
         //       channel: params.SlackChannel, // Use the parameterized Slack channel
           //     color: 'good', // or 'danger' based on the build status
          //      tokenCredentialId: params.SlackTokenCredentialId, // Use the parameterized Slack token
         //       message: "Pipeline Status: ${currentBuild.currentResult} - ${env.JOB_NAME} #${env.BUILD_NUMBER} - ${BUILD_URL}"
        //    )
       // }

        cleanup {
            cleanWs() // Clean up workspace
        }
    }

    options {
        buildDiscarder(logRotator(daysToKeepStr: '3')) // Rotate logs, keep builds for 3 days
    }
}
