---
- name: Log in to Nexus Docker registry
  shell: docker login {{ nexus_url }} --username {{ nexus_username }} --password {{ nexus_password }}

- name: Stop and remove the existing petclinic container if it exists
  docker_container:
    name: "{{ container_name }}"
    state: absent  # This stops and removes the container if it exists

- name: Pull the latest petclinic Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull  # Pull the latest image from the Nexus registry

- name: Run petclinic container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    ports:
      - "{{ app_port }}:{{ app_port }}"  # Map the given app port to 8081 inside the container
    restart_policy: always  # Ensure the container restarts if it crashes
    detach: true  # Run the container in the background
    cleanup: true  # Remove intermediate containers after build
